=== cmu-sei/juneberry/juneberry/schemas/dataset_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "definitions": {
        "plugin": {
            "type": "object",
            "properties": {
                "fqcn": { "type": "string" },
                "kwargs": { "type": "object" }
            },
            "required": [ "fqcn" ]
        }
    },
    "type": "object",
    "properties": {
        "data_type": {
            "type": "string",
            "enum": [ "image", "tabular", "tensorflow", "torchvision", "audio" ]
        },
        "description": { "type": "string" },
        "format_version": { "type": "string" },
        "url": { "type": "string" },
        "image_data": {
            "type": "object",
            "properties": {
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "directory": { "type": "string" },
                            "label": { "type": "integer" },
                            "sampling_count": { "type": "integer" },
                            "sampling_fraction": { "type": "number" }
                        },
                        "required": [ "directory" ]
                    }
                },
                "task_type": {
                    "type": "string",
                    "enum": [ "classification", "object_detection" ]
                }
            },
            "required": [ "sources", "task_type" ]
        },
        "audio_data": {
            "type": "object",
            "properties": {
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "directory": { "type": "string" },
                            "label": { "type": "integer" },
                            "sampling_count": { "type": "integer" },
                            "sampling_fraction": { "type": "number" }
                        },
                        "required": [ "directory" ]
                    }
                },
                "task_type": {
                    "type": "string",
                    "enum": [ "classification", "object_detection" ]
                }
            },
            "required": [ "sources", "task_type" ]
        },
        "label_names": { "type": "object" },
        "num_model_classes": { "type": "integer" },
        "sampling": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string",
                    "enum": [ "none", "random_fraction", "random_quantity", "round_robin" ]
                },
                "arguments": { "type": "object" }
            },
            "required": [ "algorithm" ]
        },
        "tabular_data": {
            "type": "object",
            "properties": {
                "label_index": { "type": "integer" },
                "sources": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "path": { "type": "string" },
                            "root": {
                                "type": "string",
                                "enum": [ "dataroot", "workspace", "relative" ]
                            }
                        },
                        "required": [ "path" ]
                    }
                }
            },
            "required": [ "label_index", "sources" ]
        },
        "tensorflow_data": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "load_kwargs": { "type": "object" }
            },
            "required": [ "name" ]
        },
        "timestamp": { "type": "string" },
        "torchvision_data": {
            "type": "object",
            "properties": {
                "fqcn": { "type": "string" },
                "root": { "type": "string" },
                "train_kwargs": { "type": "object" },
                "val_kwargs": { "type": "object" },
                "eval_kwargs": { "type": "object" }
            },
            "required": [ "fqcn" ]
        },
        "data_transforms": {
            "type": "object",
            "properties": {
                "seed": { "type": "number" },
                "transforms": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/plugin" }
                }
            },
            "required": [ "transforms" ]
        }
    },
    "oneOf": [
        {
            "properties": { "data_type": { "const": "image" } },
            "required": [ "data_type", "label_names", "num_model_classes", "image_data" ]
        },
        {
            "properties": { "data_type": { "const": "tabular" } },
            "required": [ "data_type", "label_names", "num_model_classes", "tabular_data" ]
        },
        {
            "properties": { "data_type": { "const": "tensorflow" } },
            "required": [ "data_type", "label_names", "num_model_classes", "tensorflow_data" ]
        },
        {
            "properties": { "data_type": { "const": "torchvision" } },
            "required": [ "data_type", "label_names", "num_model_classes", "torchvision_data" ]
        },
        {
            "properties": { "data_type": { "const": "audio" } },
            "required": [ "data_type", "label_names", "num_model_classes", "audio_data" ]
        }
    ]
}

=== cmu-sei/juneberry/data_sets/cifar10.json
{
    "data_type": "image",
    "description": "cifar10 training images, 32x32, rgb",
    "format_version": "0.2.0",
    "url": "https://www.cs.toronto.edu/~kriz/cifar.html",
    "image_data": {
        "sources": [
            {
                "directory": "cifar10/train/airplane",
                "label": 0
            },
            {
                "directory": "cifar10/train/automobile",
                "label": 1
            },
            {
                "directory": "cifar10/train/bird",
                "label": 2
            },
            {
                "directory": "cifar10/train/cat",
                "label": 3
            },
            {
                "directory": "cifar10/train/deer",
                "label": 4
            },
            {
                "directory": "cifar10/train/dog",
                "label": 5
            },
            {
                "directory": "cifar10/train/frog",
                "label": 6
            },
            {
                "directory": "cifar10/train/horse",
                "label": 7
            },
            {
                "directory": "cifar10/train/ship",
                "label": 8
            },
            {
                "directory": "cifar10/train/truck",
                "label": 9
            }
        ],
        "task_type": "classification"
    },
    "label_names": {
        "0": "airplane",
        "1": "automobile",
        "2": "bird",
        "3": "cat",
        "4": "deer",
        "5": "dog",
        "6": "frog",
        "7": "horse",
        "8": "ship",
        "9": "truck"
    },
    "num_model_classes": 10,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    },
    "timestamp": "2020-11-06T08:18:00"
}

=== cmu-sei/juneberry/data_sets/imagenet_single_batch_128.json
{
    "data_type": "image",
    "description": "Imagenet training images, restricted to a single sample",
    "format_version": "0.2.0",
    "url": "https://image-net.org/download.php",
    "image_data": {
        "sources": [
            {
                "directory": "ImageNet/train/n01440764",
                "label": 0
            }
        ],
        "task_type": "classification"
    },
    "label_names": {
        "0": "tench"
    },
    "num_model_classes": 1000,
    "sampling": {
        "algorithm": "random_quantity",
        "arguments": {
            "count": 128,
            "seed": 98754321
        }
    },
    "timestamp": "2021-06-23T08:18:00"
}

=== cmu-sei/juneberry/data_sets/yymnist_train.json
{
    "data_type": "image",
    "description": "Juneberry metadata files created using detectron2 text detection.",
    "format_version": "0.2.0",
    "image_data": {
        "sources": [
            {
                "directory": "yymnist/coco_train1k.json"
            }
        ],
        "task_type": "object_detection"
    },
    "label_names": {
        "0": "Zero",
        "1": "One",
        "2": "Two",
        "3": "Three",
        "4": "Four",
        "5": "Five",
        "6": "Six",
        "7": "Seven",
        "8": "Eight",
        "9": "Nine"
    },
    "num_model_classes": 10,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    }
}

=== cmu-sei/juneberry/data_sets/cifar10_test.json
{
    "num_model_classes": 10,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    },
    "description": "cifar10 test images, 32x32, rgb",
    "timestamp": "2021-05-25T11:18:00",
    "format_version": "3.2.0",
    "url": "https://www.cs.toronto.edu/~kriz/cifar.html",
    "label_names": {
        "0": "airplane",
        "1": "automobile",
        "2": "bird",
        "3": "cat",
        "4": "deer",
        "5": "dog",
        "6": "frog",
        "7": "horse",
        "8": "ship",
        "9": "truck"
    },
    "data_type": "image",
    "image_data": {
        "task_type": "classification",
        "sources": [
            {
                "label": 0,
                "directory": "cifar10/test/airplane"
            },
            {
                "label": 1,
                "directory": "cifar10/test/automobile"
            },
            {
                "label": 2,
                "directory": "cifar10/test/bird"
            },
            {
                "label": 3,
                "directory": "cifar10/test/cat"
            },
            {
                "label": 4,
                "directory": "cifar10/test/deer"
            },
            {
                "label": 5,
                "directory": "cifar10/test/dog"
            },
            {
                "label": 6,
                "directory": "cifar10/test/frog"
            },
            {
                "label": 7,
                "directory": "cifar10/test/horse"
            },
            {
                "label": 8,
                "directory": "cifar10/test/ship"
            },
            {
                "label": 9,
                "directory": "cifar10/test/truck"
            }
        ]
    }
}

=== cmu-sei/juneberry/data_sets/text_detect_train.json
{
    "data_type": "image",
    "description": "Juneberry metadata files created using detectron2 text detection example.",
    "format_version": "0.2.0",
    "url": "https://cocodataset.org/#download",
    "image_data": {
        "sources": [
            {
                "directory": "detectron2-text-detection/train/coco_annotations.json"
            }
        ],
        "task_type": "object_detection"
    },
    "label_names": {
        "0": "HINDI",
        "1": "ENGLISH",
        "2": "OTHER"
    },
    "num_model_classes": 3,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    },
    "timestamp": "2021-03-03T12:25:00"
}

=== cmu-sei/juneberry/models/model_tests/xor_examples/xor.json
{
    "data_type": "tabular",
    "description": "xor truth table",
    "format_version": "0.2.0",
    "tabular_data": {
        "sources": [
            {
                "root": "workspace",
                "path": "models/model_tests/xor_examples/xor.csv"
            }
        ],
        "label_index": 2
    },
    "label_names": {
        "0": "false",
        "1": "true"
    },
    "num_model_classes": 2,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    },
    "timestamp": "2021-08-16T10:00:00"
}

=== cmu-sei/juneberry/data_sets/text_detect_val.json
{
    "data_type": "image",
    "description": "Juneberry metadata files created using detectron2 text detection validation set.",
    "format_version": "0.2.0",
    "url": "https://cocodataset.org/#download",
    "image_data": {
        "sources": [
            {
                "directory": "detectron2-text-detection/val/coco_annotations.json"
            }
        ],
        "task_type": "object_detection"
    },
    "label_names": {
        "0": "HINDI",
        "1": "ENGLISH",
        "2": "OTHER"
    },
    "num_model_classes": 3,
    "sampling": {
        "algorithm": "none",
        "arguments": {}
    },
    "timestamp": "2021-03-05T10:00:00"
}

=== cmu-sei/juneberry/data_sets/imagenette_unit_test.json
{
    "data_type": "image",
    "description": "Imagenette. 160x160, rgb",
    "format_version": "0.2.0",
    "url": "https://github.com/fastai/imagenette",
    "image_data": {
        "url": "https://github.com/fastai/imagenette",
        "sources": [
            {
                "directory": "imagenette2-160/val/n01440764",
                "label": 0
            },
            {
                "directory": "imagenette2-160/val/n02102040",
                "label": 217
            },
            {
                "directory": "imagenette2-160/val/n02979186",
                "label": 482
            },
            {
                "directory": "imagenette2-160/val/n03000684",
                "label": 491
            },
            {
                "directory": "imagenette2-160/val/n03028079",
                "label": 497
            },
            {
                "directory": "imagenette2-160/val/n03394916",
                "label": 566
            },
            {
                "directory": "imagenette2-160/val/n03417042",
                "label": 569
            },
            {
                "directory": "imagenette2-160/val/n03425413",
                "label": 571
            },
            {
                "directory": "imagenette2-160/val/n03445777",
                "label": 574
            },
            {
                "directory": "imagenette2-160/val/n03888257",
                "label": 701
            }
        ],
        "task_type": "classification"
    },
    "label_names": {
        "0": "tench",
        "217": "English_springer",
        "482": "cassette_player",
        "491": "chain_saw",
        "497": "church",
        "566": "French_horn",
        "569": "garbage_truck",
        "571": "gas_pump",
        "574": "golf_ball",
        "701": "parachute"
    },
    "num_model_classes": 1000,
    "sampling": {
        "algorithm": "random_quantity",
        "arguments": {
            "count": 10,
            "seed": 98754321
        }
    },
    "timestamp": "2020-11-06T08:18:00"
}
