=== cmu-sei/juneberry/juneberry/schemas/experiment_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/cmu-sei/juneberry/main/juneberry/schemas/experiment_schema.json",
    "type": "object",
    "properties": {
        "description": { "type": "string" },
        "format_version": { "type": "string" },
        "filter": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "tag": { "type": "string" },
                    "cmd": {
                        "type": "array",
                        "items": { "type": "string" }
                    },
                    "inputs": {
                        "type": "array",
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "models": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "filters": {
                        "type": "array",
                        "items": { "type": "string" }
                    },
                    "name": { "type": "string" },
                    "onnx": { "type": "boolean"},
                    "tests": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "classify": { "type": "integer" },
                                "dataset_path": { "type": "string" },
                                "filters": {
                                    "type": "array",
                                    "items": { "type": "string" }
                                },
                                "tag": { "type": "string" },
                                "use_train_split": { "type": "boolean" },
                                "use_val_split": { "type": "boolean" }
                            },
                            "required": [ "dataset_path", "tag" ]
                        }
                    },
                    "version": { "type": "string" }
                },
                "required": [ "name", "tests" ]
            },
            "minItems": 1
        },
        "reports": {
            "type": "array",
            "items": {
                "allOf": [{ "$ref": "https://raw.githubusercontent.com/cmu-sei/juneberry/fd6afebc67bbd3853d09fa7625d847249289df57/juneberry/schemas/report_schema.json/$defs/report"}],
                "properties": {
                    "classes": { "type": "string"},
                    "tests": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "tag": { "type": "string" },
                                        "classes": { "type": "string" }
                                    },
                                    "required": [ "tag" ]
                                }
                            }
                }
            }
        },
        "timestamp": { "type": "string" }
    },
    "required": [
        "models",
        "reports"
    ]
}

=== cmu-sei/juneberry/experiments/smokeTests/od/cpu/config.json
{
    "description": "Unit test for object detection platforms using CPU training.",
    "format_version": "0.2.0",
    "models": [
        {
            "name": "text_detect/dt2/ut",
            "tests": [
                {
                    "dataset_path": "data_sets/text_detect_val.json",
                    "tag": "ut_val_dt2"
                }
            ]
        }
    ],
    "reports": [
        {
            "description": "Builds PR plots for the dt2 model.",
            "iou": 0.5,
            "output_dir": "ut_val_dt2",
            "tests": [
                {
                    "tag": "ut_val_dt2"
                }
            ],
            "type": "plot_pr"
        },
        {
            "csv_name": "OD System Test Summary.csv",
            "description": "Simple OD System Test Summary",
            "output_name": "System OD Test Summary.md",
            "type": "summary"
        }

    ],
    "timestamp": "2020-06-10T08:29:00"
}

=== cmu-sei/juneberry/experiments/smokeTests/od/gpu/config.json
{
    "description": "Unit test for object detection platforms using GPU training.",
    "format_version": "0.2.0",
    "models": [
        {
            "name": "text_detect/dt2/ut",
            "tests": [
                {
                    "dataset_path": "data_sets/text_detect_val.json",
                    "tag": "ut_val_dt2"
                }
            ]
        },
        {
            "name": "text_detect/mmd/ut",
            "tests": [
                {
                    "dataset_path": "data_sets/text_detect_val.json",
                    "tag": "ut_val_mmd"
                }
            ]
        }
    ],
    "reports": [
        {
            "description": "Builds PR plots for the dt2 model.",
            "fqcn": "juneberry.reporting.pr.PRCurve",
            "kwargs": {
                "iou": 0.5,
                "output_dir": "ut_val_dt2"
            },
            "tests": [
                {
                    "tag": "ut_val_dt2"
                }
        ]
        },
        {
            "description": "Builds PR plots for the mmd model.",
            "fqcn": "juneberry.reporting.pr.PRCurve",
            "kwargs": {
                "iou": 0.5,
                "output_dir": "ut_val_mmd"
            },
            "tests": [
                {
                    "tag": "ut_val_mmd"
                }
            ]
        },
        {
            "description": "Combines PR curves for both platforms on the same plot. Slight increase to IoU.",
            "fqcn": "juneberry.reporting.pr.PRCurve",
            "kwargs": {
                "iou": 0.55,
                "output_dir": "ut_val_combined"
            },
            "tests": [
                {
                    "tag": "ut_val_dt2"
                },
                {
                    "tag": "ut_val_mmd"
                }
            ]
        },
        {
            "description": "System OD Test Summary.md",
            "fqcn": "juneberry.reporting.summary.Summary",
            "kwargs": {
                "csv_filename": "OD System Test Summary.csv",
                "md_filename": "System OD Test Summary.md"
            }
        }
    ],
    "timestamp": "2022-04-15T07:40:00"
}
