=== cmu-sei/juneberry/juneberry/schemas/model_schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "definitions": {
        "plugin_item": {
            "type": "object",
            "properties": {
                "fqcn": { "type": "string" },
                "kwargs": { "type": "object" }
            },
            "required": [ "fqcn" ]
        }
    },
    "type": "object",
    "description": "A configuration for training and running a model file.",
    "properties": {
        "batch_size": { "type": "integer" },
        "description": { "type": "string" },
        "detectron2": {
            "type": "object",
            "properties": {
                "disable_val_loss": { "type": "boolean" },
                "metric_interval": { "type": "integer" },
                "overrides": { "type": "array" },
                "supplements": {
                    "type": "array",
                    "items": { "type": "string" }
                }
            },
            "required": [ ]
        },
        "epochs": { "type": "integer" },
        "evaluation_metrics": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "evaluation_metrics_formatter": { "$ref": "#/definitions/plugin_item" },
        "evaluation_transforms": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "evaluation_target_transforms": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "evaluator": { "$ref": "#/definitions/plugin_item" },
        "format_version": { "type": "string" },
        "label_mapping": { "type": [ "string", "object" ] },
        "mmdetection": {
            "type": "object",
            "properties": {
                "load_from": { "type": "string" },
                "overrides": { "type": "object" },
                "test_pipeline_stages": { "type": "array" },
                "train_pipeline_stages": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "mode": { "type": "string" },
                            "name": { "type": "string" },
                            "stage": { "type": "object" },
                            "tupleize": { "type": "boolean" }
                        },
                        "required": [ "name", "stage" ]
                    }
                }
            },
            "required": [ "load_from" ]
        },
        "model_architecture": {
            "type": "object",
            "properties": {
                "args": { "type": "object" },
                "module": { "type": "string" },
                "previous_model": { "type": "string" },
                "previous_model_version": { "type": "string" }
            },
            "required": [ "module" ]
        },
        "model_transforms": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "platform": {
            "type": "string",
            "enum": [ "detectron2", "mmdetection", "pytorch", "pytorch_privacy", "tensorflow", "tfgloro" ]
        },
        "preprocessors": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "pytorch": {
            "type": "object",
            "properties": {
                "accuracy_args": { "type": "object" },
                "accuracy_fn": { "type": "string" },
                "loss_args": { "type": "object" },
                "loss_fn": { "type": "string" },
                "lr_schedule_fn": { "type": "string" },
                "lr_schedule_args": { "type": "object" },
                "lr_step_frequency": {
                    "type": "string",
                    "enum": [ "epoch", "batch" ]
                },
                "optimizer_fn": { "type": "string" },
                "optimizer_args": { "type": "object" }
            },
            "required": [ ]
        },
        "seed": { "type": "integer" },
        "stopping_criteria": {
            "type": "object",
            "properties": {
                "direction": { "type": "string", "enum": [ "le", "ge" ] },
                "history_key": { "type": "string", "enum": [ "loss", "accuracy", "val_loss", "val_accuracy" ] },
                "abs_tol": { "type": "number" },
                "plateau_count": { "type": "integer" },
                "threshold": { "type": "number" }
            },
            "required": [ ]
        },
        "task": {
            "type": "string",
            "enum": [ "classification", "objectDetection" ]
        },
        "tensorflow": {
            "type": "object",
            "properties": {
                "callbacks": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/plugin_item" }
                },
                "loss_args": { "type": "object" },
                "loss_fn": { "type": "string" },
                "lr_schedule_args": { "type": "object" },
                "lr_schedule_fn": { "type": "string" },
                "metrics": {
                    "type": "array",
                    "items": {
                        "oneOf": [
                            { "type": "string" },
                            { "$ref": "#/definitions/plugin_item" }
                        ]
                    }
                },
                "optimizer_args": { "type": "object" },
                "optimizer_fn": { "type": "string" }
            },
            "required": [ "loss_fn", "optimizer_fn" ]
        },
        "timestamp": { "type": "string" },
        "trainer": { "$ref": "#/definitions/plugin_item" },
        "training_dataset_config_path": { "type": "string" },
        "training_transforms": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "training_target_transforms": {
            "type": "array",
            "items": { "$ref": "#/definitions/plugin_item" }
        },
        "validation": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "type": "string",
                    "enum": [ "from_file", "none", "random_fraction", "tensorflow", "torchvision" ]
                },
                "arguments": {
                    "type": "object",
                    "properties": {
                        "file_path": { "type": "string" },
                        "fraction": { "type": "number" },
                        "seed": { "type": "integer" }
                    },
                    "required": [ ]
                }
            },
            "oneOf": [
                {
                    "properties": {
                        "algorithm": { "const": "from_file" },
                        "arguments": { "required": [ "file_path" ] }
                    }
                },
                {
                    "properties": {
                        "algorithm": { "const": "none" },
                        "arguments": { "required": [ ] }
                    }
                },
                {
                    "properties": {
                        "algorithm": { "const": "random_fraction" },
                        "arguments": { "required": [ "fraction" ] }
                    }
                },
                {
                    "properties": {
                        "algorithm": { "const": "tensorflow" },
                        "arguments": { "required": [ ] }
                    }
                },
                {
                    "properties": {
                        "algorithm": { "const": "torchvision" },
                        "arguments": { "required": [ ] }
                    }
                }
            ],
            "required": [ "algorithm" ]
        }
    },
    "required": [
        "batch_size",
        "format_version",
        "model_architecture",
        "training_dataset_config_path",
        "validation"
    ]
}

=== cmu-sei/juneberry/models/tabular_multiclass_sample/config.json
{
    "batch_size": 1500,
    "description": "Mutliclass csv dataset for unit testing",
    "epochs": 100,
    "format_version": "0.2.0",
    "model_architecture": {
        "args": {
            "num_classes": 3
        },
        "module": "juneberry.architectures.pytorch.sample_tabular_nn.MultiClassModel"
    },
    "platform": "pytorch",
    "pytorch": {
        "loss_fn": "torch.nn.CrossEntropyLoss",
        "optimizer_args": {
            "lr": 1.0
        },
        "optimizer_fn": "torch.optim.SGD"
    },
    "seed": 4210592948,
    "task": "classification",
    "timestamp": "2021-03-01T10:00:00",
    "training_dataset_config_path": "models/tabular_multiclass_sample/train_data_config.json",
    "validation": {
        "algorithm": "from_file",
        "arguments": {
            "file_path": "models/tabular_multiclass_sample/val_data_config.json"
        }
    }
}

=== cmu-sei/juneberry/models/text_detect/mmd/all/config.json
{
    "batch_size": 4,
    "description": "Trains an object detector with MMDetection using the Sample TextDetection data set.",
    "epochs": 15,
    "evaluation_metrics": [
        {
            "fqcn": "juneberry.metrics.metrics.Coco",
            "kwargs": {
                "iou_threshold": 0.5,
                "max_det": 100,
                "tqdm": false
            },
            "formatter": {
                "fqcn": "juneberry.metrics.format.Coco",
                "kwargs": {
                }
            }
        }
    ],
    "evaluation_transforms": [],
    "evaluator": {
        "fqcn": "juneberry.mmdetection.evaluator.Evaluator"
    },
    "format_version": "0.2.0",
    "mmdetection": {
        "load_from": "https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_caffe_dc5_mstrain_1x_coco/faster_rcnn_r50_caffe_dc5_mstrain_1x_coco_20201028_233851-b33d21b9.pth",
        "overrides": {
            "model.roi_head.bbox_head.num_classes": 3,
            "optimizer.lr": 0.0025
        }
    },
    "model_architecture": {
        "module": "faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py"
    },
    "platform": "mmdetection",
    "pytorch": {
        "deterministic": true
    },
    "seed": 4210592948,
    "task": "objectDetection",
    "timestamp": "2021-03-03T10:00:00",
    "trainer": {
        "fqcn": "juneberry.mmdetection.trainer.MMDTrainer"
    },
    "training_dataset_config_path": "data_sets/text_detect_train.json",
    "training_transforms": [],
    "validation": {
        "algorithm": "random_fraction",
        "arguments": {
            "fraction": 0.2,
            "seed": 3554237221
        }
    }
}

=== cmu-sei/juneberry/models/text_detect/dt2/ut/config.json
{
    "batch_size": 4,
    "description": "Unit test for an object detector on the TextDetection data set.",
    "detectron2": {
        "overrides": [
            "SOLVER.BASE_LR",
            0.0025,
            "SOLVER.REFERENCE_WORLD_SIZE",
            1
        ]
    },
    "epochs": 1,
    "evaluation_metrics": [
       {
           "fqcn": "juneberry.metrics.metrics.Coco",
           "kwargs": {
               "iou_threshold": 0.5,
               "max_det": 100,
               "tqdm": false
           },
           "opt_args": {
             "formatter": {
               "fqcn": "juneberry.metrics.format.Coco",
               "kwargs": {
               }
             }
           }
       }
    ],
    "evaluation_transforms": [],
    "evaluator": {
        "fqcn": "juneberry.detectron2.evaluator.Evaluator"
    },
    "format_version": "0.2.0",
    "model_architecture": {
        "args": {
            "num_classes": 3
        },
        "module": "COCO-Detection/faster_rcnn_R_50_FPN_1x.yaml"
    },
    "platform": "detectron2",
    "pytorch": {
        "deterministic": true
    },
    "seed": 4210592948,
    "task": "objectDetection",
    "timestamp": "2021-03-03T10:00:00",
    "trainer": {
        "fqcn": "juneberry.detectron2.trainer.Detectron2Trainer"
    },
    "training_dataset_config_path": "data_sets/text_detect_val.json",
    "training_transforms": [],
    "validation": {
        "algorithm": "random_fraction",
        "arguments": {
            "fraction": 0.2,
            "seed": 3554237221
        }
    }
}

=== cmu-sei/juneberry/docs/vignettes/vignette1/configs/config.json
{
    "batch_size": 128,
    "description": "CIFAR-10 ResNet Model Configuration",
    "epochs": 182,
    "evaluation_transforms":[
        {
            "fqcn": "torchvision.transforms.ToTensor"
        },
        {
            "fqcn": "torchvision.transforms.Normalize",
            "kwargs": {
                "mean": [
                    0.4914,
                    0.4822,
                    0.4465
                ],
                "std": [
                    0.2023,
                    0.1994,
                    0.2010
                ]
            }
        }
    ],
    "evaluator": {
        "fqcn": "juneberry.pytorch.evaluation.evaluator.Evaluator"
    },
    "format_version": "0.2.0",
    "model_architecture": {
        "module": "juneberry.architectures.pytorch.resnet_simple.Resnet32x32",
        "args": {
            "img_width": 32,
            "img_height": 32,
            "channels": 3,
            "num_classes": 10,
            "layers": 20
        }
    },
    "model_transforms": [
    {
        "fqcn": "juneberry.pytorch.model_transforms.LogModelSummary",
        "kwargs": {
            "image_shape": [
                3,
                32,
                32
            ]
        }
    }
    ],
    "pytorch": {
        "loss_fn": "torch.nn.CrossEntropyLoss",
        "optimizer_fn": "torch.optim.SGD",
        "optimizer_args": {
            "lr": 0.1,
            "momentum": 0.9,
            "weight_decay": 0.0001
        },
        "lr_schedule_fn": "torch.optim.lr_scheduler.MultiStepLR",
        "lr_schedule_args": {
            "milestones": [92, 138],
            "gamma": 0.1
        }
    },
    "seed": 31415,
    "task": "classification",
    "timestamp": "2022-02-03T08:30:00",
    "trainer": {
        "fqcn": "juneberry.pytorch.classifier_trainer.ClassifierTrainer"
    },
    "training_dataset_config_path": "data_sets/torchvision/cifar10.json",
    "training_transforms": [
        {
            "fqcn": "juneberry.transforms.random_crop_mirror.RandomCropMirror",
            "kwargs": {
                "width_pixels": 4,
                "height_pixels": 4,
                "mirror": true
            }
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.SizeCheckImageTransform",
            "kwargs": {
                "width": 32,
                "height": 32,
                "mode": "RGB"
            }
        },
        {
            "fqcn": "torchvision.transforms.ToTensor"
        },
        {
            "fqcn": "torchvision.transforms.Normalize",
            "kwargs": {
                "mean": [
                    0.4914,
                    0.4822,
                    0.4465
                ],
                "std": [
                    0.2023,
                    0.1994,
                    0.2010
                ]
            }
        }
    ],
    "validation": {
        "algorithm": "random_fraction",
        "arguments": {
            "fraction": 0.1,
            "seed": 31415
        }
    }
}

=== cmu-sei/juneberry/models/text_detect/dt2/all/config.json
{
    "batch_size": 4,
    "description": "Trains an object detector using the Sample TextDetection data set.",
    "detectron2": {
        "overrides": [
            "SOLVER.BASE_LR",
            0.0025,
            "SOLVER.REFERENCE_WORLD_SIZE",
            1
        ]
    },
    "epochs": 15,
    "evaluation_transforms": [
        {
            "fqcn": "juneberry.detectron2.transforms.DT2Logger",
            "kwargs": {
                "msg": "eval"
            }
        }
    ],
    "format_version": "0.2.0",
    "model_architecture": {
        "args": {
            "num_classes": 3
        },
        "module": "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
    },
    "platform": "detectron2",
    "pytorch": {
        "deterministic": true
    },
    "seed": 4210592948,
    "task": "objectDetection",
    "timestamp": "2021-03-03T10:00:00",
    "training_dataset_config_path": "data_sets/text_detect_train.json",
    "training_transforms": [
        {
            "fqcn": "juneberry.detectron2.transforms.DT2Logger",
            "kwargs": {
                "msg": "train"
            }
        }
    ],
    "validation": {
        "algorithm": "from_file",
        "arguments": {
            "file_path": "data_sets/text_detect_val.json"
        }
    }
}

=== cmu-sei/juneberry/models/imagenette_224x224_rgb_unit_test_tf_resnet50/config.json
{
    "batch_size": 20,
    "description": "Unit test using a pretrained tensorflow resnet50 model with small dataset.",
    "epochs": 5,
    "evaluation_transforms": [
        {
            "fqcn": "juneberry.transforms.image.ResizePad",
            "kwargs": { "height": 224, "width": 224 }
        },
        {
            "fqcn": "juneberry.transforms.image.ConvertMode",
            "kwargs": { "mode": "RGB" }
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.SizeCheckImageTransform",
            "kwargs": { "height": 224, "mode": "RGB", "width": 224 }
        }
    ],
    "evaluator": {
        "fqcn": "juneberry.tensorflow.evaluation.evaluator.Evaluator"
    },
    "format_version": "0.2.0",
    "label_mapping": "data_sets/label_mappings/imagenet.json",
    "model_architecture": {
        "args": {
            "channels": 3,
            "img_height": 224,
            "img_width": 224,
            "num_classes": 1000
        },
        "module": "juneberry.architectures.tensorflow.resnet_pretrained_reference.Resnet50Pretrained"
    },
    "platform": "tensorflow",
    "tensorflow": {
        "loss_fn": "tensorflow.keras.losses.SparseCategoricalCrossentropy",
        "metrics": [ "accuracy" ],
        "optimizer_args": {
            "learning_rate": 0.01
        },
        "optimizer_fn": "tensorflow.keras.optimizers.SGD"
    },
    "seed": 4210592948,
    "task": "classification",
    "timestamp": "2021-03-02T13:30:00",
    "training_dataset_config_path": "data_sets/imagenette_unit_train.json",
    "training_transforms": [
        {
            "fqcn": "juneberry.transforms.image.ResizePad",
            "kwargs": { "height": 224, "width": 224 }
        },
        {
            "fqcn": "juneberry.transforms.image.ConvertMode",
            "kwargs": { "mode": "RGB" }
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.SizeCheckImageTransform",
            "kwargs": { "height": 224, "mode": "RGB", "width": 224 }
        }
    ],
    "validation": {
        "algorithm": "random_fraction",
        "arguments": {
            "fraction": 0.2,
            "seed": 3554237221
        }
    }
}

=== cmu-sei/juneberry/models/imagenette_160x160_rgb_unit_test_pyt_resnet18/config.json
{
    "batch_size": 20,
    "description": "Unit test using a pretrained pytorch resnet18 model with small dataset.",
    "epochs": 5,
    "evaluation_transforms": [
        {
            "fqcn": "juneberry.transforms.image.ResizePad",
            "kwargs": {
                "height": 160,
                "width": 160
            }
        },
        {
            "fqcn": "juneberry.transforms.image.ConvertMode",
            "kwargs": {
                "mode": "RGB"
            }
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.SizeCheckImageTransform",
            "kwargs": {
                "height": 160,
                "mode": "RGB",
                "width": 160
            }
        }
    ],
    "evaluator": {
        "fqcn": "juneberry.pytorch.evaluator.PytorchEvaluator"
    },
    "format_version": "0.2.0",
    "label_mapping": "data_sets/label_mappings/imagenet.json",
    "model_architecture": {
        "args": {
            "channels": 3,
            "img_height": 160,
            "img_width": 160,
            "num_classes": 1000
        },
        "module": "juneberry.architectures.pytorch.pytv_resnet18_pretrained_reference.ReferenceResnet18"
    },
    "platform": "pytorch",
    "pytorch": {
        "accuracy_args": {
            "normalize": true
        },
        "accuracy_fn": "sklearn.metrics.accuracy_score",
        "deterministic": true,
        "loss_fn": "torch.nn.CrossEntropyLoss",
        "lr_schedule_args": {
            "gamma": 0.5,
            "milestones": [
                3,
                5
            ]
        },
        "lr_schedule_fn": "MultiStepLR",
        "optimizer_args": {
            "lr": 0.01
        },
        "optimizer_fn": "torch.optim.SGD"
    },
    "seed": 4210592948,
    "task": "classification",
    "timestamp": "2021-03-02T13:30:00",
    "trainer": {
        "fqcn": "juneberry.pytorch.classifier_trainer.ClassifierTrainer"
    },
    "training_dataset_config_path": "data_sets/imagenette_unit_train.json",
    "training_transforms": [
        {
            "fqcn": "juneberry.transforms.image.ResizePad",
            "kwargs": {
                "height": 160,
                "width": 160
            }
        },
        {
            "fqcn": "juneberry.transforms.image.ConvertMode",
            "kwargs": {
                "mode": "RGB"
            }
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.SizeCheckImageTransform",
            "kwargs": {
                "height": 160,
                "mode": "RGB",
                "width": 160
            }
        },
        {
            "fqcn": "torchvision.transforms.ToTensor"
        },
        {
            "fqcn": "juneberry.transforms.debugging_transforms.NoOpTensorTransform",
            "kwargs": {
                "name": "NoOpTensorTransformer"
            }
        }
    ],
    "validation": {
        "algorithm": "random_fraction",
        "arguments": {
            "fraction": 0.2,
            "seed": 3554237221
        }
    }
}

=== cmu-sei/juneberry/models/onnx/FasterRCNN-10/config.json
{
    "batch_size": 20,
    "description": "Minimum required model config for evaluating the Faster R-CNN ONNX model available from https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn",
    "evaluator": {
        "fqcn": "juneberry.onnx.evaluator.Evaluator",
        "kwargs": {
            "loader": "juneberry.onnx.faster_rcnn.DataLoader",
            "output": "juneberry.onnx.faster_rcnn.EvaluationOutput",
            "procedure": "juneberry.onnx.faster_rcnn.EvaluationProcedure"
        }
    },
    "format_version": "0.2.0",
    "model_architecture": {
        "args": {},
        "module": ""
    },
    "seed": 12345,
    "task": "objectDetection",
    "training_dataset_config_path": "data_sets/coco2017_val.json",
    "validation": {
        "algorithm": "none"
    }
}
